import React from 'react'
import { Link } from 'react-router-dom'
import { baseImgUrl } from '../../helpers/functions-general'
import { topLiveGames } from './data'
import { FaAngleDown } from 'react-icons/fa'
import { IoChevronDown } from "react-icons/io5";


const TopLiveGames = ({sliderHeader}) => {
  return (
    <div className='px-4 py-2'>
        <div className='flex justify-between items-center mb-5'>
            <div className='flex flex-col gap-2'> 
                <button className='text-white text-2xl'>{sliderHeader}</button>
                <small className='text-[#AAA]'>Auto-generated by Youtube</small>
            </div>
            <Link className='text-[#3ea6ff] py-2 px-4 rounded-full text-lg'>View all</Link>
        </div>

        <div className='flex items-center gap-3 mb-5 p-2 flex-wrap'>
            {topLiveGames.map((item,key) => (
                <button className='top-content' key={key}>
                    <img src={`${baseImgUrl}/video/${item.img}`} alt="" className='rounded-xl mb-2 w-[16rem] h-full max-h-[30rem] object-cover'/>
                    <h1 className='text-white text-lg text-left'>{item.title}</h1>
                    <p className='text-[#aaa] tracking-wider text-left'>{item.views}</p>
                </button>
            ))}
        </div>

        <div className='text-white flex items-center justify-center py-2 relative'>
            <button className='show-more py-[8px] rounded-full border border-[#3f3f3f] font-medium w-[25rem] relative'>Show more
                <IoChevronDown className='text-2xl absolute right-32 top-2'/>
            </button>
            <span className='w-[36.9rem] h-[0.1rem] absolute left-0 bg-[#3f3f3f]'></span>
            <span className='w-[36.9rem] h-[0.1rem] absolute right-0 bg-[#3f3f3f]'></span>
        </div>
        
        
    </div>
  )
}

export default TopLiveGames